[database]
host     = 127.0.0.1
port     = 3306
user     = root
password = root
name     = bibinatorDB

[setup]
mode                = original_files  
; mode                = backup 
; mode                = validate   
run_tests           = true
drop_staging_tables = true
export_final_tables = false
create_backup       = true

[app]
port = 8501
mode = run   
; mode = test_queries